### ISSUE TITLE
Add KonrWings, Default Backgrounds

### ISSUE THREAD

**Issue by nebrassy** [CriticalFlaw/rayshud-Installer#2]
I noticed that there isn't an option to enable KonrWings in the installer, it's also not possible to enable multiple crosshairs or choose a different color for each.
I for one use green basicdot with white konrwings

can you add those options?
thanks.

**Comment by nebrassy** [comment]
also since I'm here, is it possible to have the default backgrounds? like not just the gray upward/dustbowl, but all the default backgrounds and the class overlay?

**Comment by CriticalFlaw** [comment]
- [ ] Include all default backgrounds, not just Upward/Dustbowl
- [ ] Add KonrWings to the crosshair selection

Multiple crosshairs are not possible by design, and it would require a lot of backend work to implement. Anyone else willing to do the work is welcome to do so and create a pull request.

I'm not entirely sure what you mean by 'class overlay' do you mean the class images on the main menu?

**Comment by nebrassy** [comment]
yeah like the Pyro with the jetpack which was added with Jungle inferno.
what's hard about multiple crosshairs?, I just set enabled and visible to 1 for the ones I want and set fgcolor for each one

**Comment by CriticalFlaw** [comment]
- [ ] Implement class images on the main menu

The installer uses a single crosshair node, not multiple individual nodes for each crosshair style. This was done for easier maintenance and to reduce risk of things breaking when hudlayout.res is updated. Additionally to add the option to have multiple crosshairs would require to fit it into an already cramped UI.

**Comment by nebrassy** [comment]
ah yeah I get what you mean, guess I can do it manually, still better than manually updating everything, for the UI it shouldn't be hard if you chose to make it, just replace the enable crosshairs checkbox with enable selected crosshair

**Comment by CriticalFlaw** [comment]
I may look into it later for sure. For now I've pushed out code changes to both the installer (https://github.com/CriticalFlaw/rayshud-Installer/commit/50cc7ccbff1b262286430f6a12c89c71a057ed81) and rayshud (https://github.com/raysfire/rayshud/commit/ddb12d0b333c80e38ee9a581efdfede214d6456b) to add the KonrWings, class images and maybe fix not every default background being displayed.

It won't be available until I'm able to test everything this evening. But the default background fix should be in effect because it was only a change to rayshud

**Comment by nebrassy** [comment]
have you tested the default backgrounds?, I believe I'm still only getting gray upward, 2fort and dustbowl i think

**Comment by CriticalFlaw** [comment]
Not counting the event specific backgrounds, those four are the only defaults

**Comment by nebrassy** [comment]
ah yeah you're correct, it's those in addition to gravel pit and mannworks, is it possible to have event/halloween backgrounds too, maybe just when an event is active or would that be too much work?
