### ISSUE TITLE
Ubercharge bar colors, Ammo colors  not updating

### ISSUE THREAD

**Issue by thatguyJD** [CriticalFlaw/rayshud-Installer#8]
When updating the colors on the installer for the ubercharge bar, full uber color/flash, ammo. It doesn't  update in the game. For example I use blue for my ammo so the ubercharge percentage should be blue but it is white. And the full ubercharge bar stays white and flashes white when I have set it to orange flash to pink.
There was a short period where the number color would be blue which was on my first life after installing the hud and after ubering once or dying once (not sure which it was) it went to white and stayed white.

And may as well add it in here, there's no option to change the damage number color that shows above the health bar. For some reason it's an aqua color and I wish to change it

**Comment by CriticalFlaw** [comment]
Please retest this with the latest installer version, it might be a incompatibility between the installer and the latest rayshud. Also note that color changes do not take effect until you restart the game, because the change is applied to a clientscheme file which is only read when the game is first being loaded.

Ever since Valve made it so that the damage color could be changed in the advanced options menu, the way of changing them through a hud no longer works. I don't know if they've fixed that since then. That's why the option won't be added to the installer and you're better off modifing it yourself in the aforementioned advanced options menu.
